{
 "title": "Node State",
 "tags": [ "lightning-network" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "namespace", "label": "namespace", "query": "label_values(namespace)" },
   {
    "name": "node",
    "label": "node",
    "query": "label_values(lnd_chain_block_timestamp{namespace=\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Channel Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "lnd_channels_pending_total{namespace=\"$namespace\",pod=\"$node\"}",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "lnd_channels_active_total{namespace=\"$namespace\",pod=\"$node\"}",
     "legendFormat": "active"
    },
    {
     "expr": "lnd_channels_inactive_total{namespace=\"$namespace\",pod=\"$node\"}",
     "legendFormat": "inactive"
    }
   ]
  },
  {
   "title": "Total Node Funds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "currencyBTC" }
   ],
   "targets": [
    {
     "expr": "lnd_channels_pending_balance_sat{namespace=\"$namespace\",pod=\"$node\"} > 0",
     "legendFormat": "pending_open_sat"
    },
    {
     "expr": "lnd_channels_open_balance_sat{namespace=\"$namespace\",pod=\"$node\"}",
     "legendFormat": "channels_sat"
    },
    {
     "expr": "lnd_wallet_balance_unconfirmed_sat{namespace=\"$namespace\",pod=\"$node\"} > 0",
     "legendFormat": "unconf_balance_sat"
    },
    {
     "expr": "lnd_wallet_balance_confirmed_sat{namespace=\"$namespace\",pod=\"$node\"}",
     "legendFormat": "conf_balance_sat"
    }
   ]
  },
  {
   "title": "Channel Bandwidth",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "currencyBTC" }
   ],
   "targets": [
    {
     "expr": "sum(lnd_channels_bandwidth_outgoing_sat{namespace=\"$namespace\",pod=\"$node\"})",
     "legendFormat": "outgoing_channel_bandwidth_sat"
    },
    {
     "expr": "sum(lnd_channels_bandwidth_incoming_sat{namespace=\"$namespace\",pod=\"$node\"})",
     "legendFormat": "incoming_channel_bandwidth"
    }
   ]
  },
  {
   "title": "Pending Channel HTLCs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "lnd_channels_pending_htlc_count{namespace=\"$namespace\",pod=\"$node\"} > 0",
     "legendFormat": "cid: {{ chan_id }}"
    }
   ]
  },
  {
   "title": "Most Active Channels (Sat Transit)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "currencyBTC" }
   ],
   "targets": [
    {
     "expr": "topk(5, lnd_channels_sent_sat{namespace=\"$namespace\",pod=\"$node\"} + lnd_channels_received_sat{namespace=\"$namespace\",pod=\"$node\"} > 0)",
     "legendFormat": "cid: {{ chan_id }}"
    }
   ]
  },
  {
   "title": "Most Active Channels (Updates)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, lnd_channels_updates_count{namespace=\"$namespace\",pod=\"$node\"})",
     "legendFormat": "cid: {{ chan_id }}"
    }
   ]
  },
  {
   "title": "Total Chan Commit Fees",
   "type": "graph",
   "description": "Total fees in sats across all active commitments ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(lnd_channels_commit_fee{namespace=\"$namespace\",pod=\"$node\"})",
     "legendFormat": "total_commit_fees"
    }
   ]
  },
  {
   "title": "Channel Commitment Fee Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(lnd_channels_fee_per_kw{namespace=\"$namespace\",pod=\"$node\"})",
     "legendFormat": "max_fee_per_kw"
    },
    {
     "expr": "min(lnd_channels_fee_per_kw{namespace=\"$namespace\",pod=\"$node\"})",
     "legendFormat": "min_fee_per_kw"
    },
    {
     "expr": "avg(lnd_channels_fee_per_kw{namespace=\"$namespace\",pod=\"$node\"})",
     "legendFormat": "avg_fee_per_kw"
    }
   ]
  },
  {
   "title": "Incoming Bandwidth by Channel",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "currencyBTC" }
   ],
   "targets": [
    {
     "expr": "lnd_channels_bandwidth_incoming_sat{namespace=\"$namespace\",pod=\"$node\"} > 20000",
     "legendFormat": "cid: {{ chan_id }}"
    }
   ]
  },
  {
   "title": "Channel Uptime Percentage",
   "type": "graph",
   "description": "Uptime percentage of remote peer that we have the channel with.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "lnd_channel_uptime_percentage{namespace=\"$namespace\",pod=\"$node\"}",
     "legendFormat": "cid: {{ chan_id }}"
    }
   ]
  },
  {
   "title": "Outgoing Channel Bandwidth by Chan ID",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "currencyBTC" }
   ],
   "targets": [
    {
     "expr": "lnd_channels_bandwidth_outgoing_sat{namespace=\"$namespace\",pod=\"$node\"} > 20000",
     "legendFormat": "chan_id: {{ chan_id }}"
    }
   ]
  },
  {
   "title": "Closed Channels",
   "type": "graph",
   "description": "Uptime percentage of remote peer that we have the channel with.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "lnd_closed_channels_total{namespace=\"$namespace\",pod=\"$node\"}",
     "legendFormat": "{{close_type}}"
    }
   ]
  }
 ]
}