version: "3.7"
services:
 
  lndmon:
    build: .
    ports:
      - "9092:9092"
    restart: always
    volumes:
      - ${TLS_CERT_PATH?}:/root/.lnd/tls.cert
      - ${MACAROON_PATH?}:/root/.lnd/
    command: --prometheus.listenaddr=0.0.0.0:9092 --lnd.network=$LND_NETWORK --lnd.host=$LND_HOST --lnd.macaroondir=/root/.lnd --lnd.tlspath=/root/.lnd/tls.cert

  prometheus:
    image: prom/prometheus:v2.10.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-storage:/prometheus
    # Reasoning behind Prometheus command query flags:
    # --query.max-samples: each Prometheus data sample is 16 bytes.
    #                      16B * 31250000 = 1/2 GB.
    # --query.max-concurrency: the max # of concurrent queries (default is 20).
    # these parameters are intended to limit the amount of memory Prometheus
    # uses for its queries to ~1GB, because it's sensitive to OOMs.
    command: "--config.file=/etc/prometheus/prometheus.yml --query.max-samples=31250000 --query.max-concurrency=2"
    ports:
      - "9090:9090"
    restart: always
    depends_on:
      - lndmon

  grafana:
    image: grafana/grafana:6.2.0
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - grafana-storage:/var/lib/grafana

  post_start:
    build: ./post_start
    depends_on:
      - grafana

volumes:
  grafana-storage:
  prometheus-storage:

networks:
  default:
    external: true
    name: 2_default
