apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lndmon.fullname" . }}
  labels:
    {{- include "lndmon.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "lndmon.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "lndmon.labels" . | nindent 8 }}
	{{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "lndmon.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ '/bin/lndmon']
          args:
            - '--prometheus.listenaddr={{ .Values.args.prometheus.listenAddr }}'
            - '--prometheus.logdir={{ .Values.args.prometheus.logDir }}'
            - '--prometheus.maxlogfiles={{ .Values.args.prometheus.maxLogFiles }}'
            - '--prometheus.maxlogfilesize={{ .Values.args.prometheus.maxLogFileSizeMB }}'
            - '--lnd.host={{ .Values.args.lnd.host }}'
            - '--lnd.network={{ .Values.args.lnd.network }}'
            - '--lnd.macaroondir={{ .Values.args.lnd.macaroonDir }}'
            - '--lnd.macaroonname={{ .Values.args.lnd.macaroonName }}'
            - '--lnd.rpctimeout={{ .Values.args.lnd.rpcTimeout }}'
            - '--lnd.tlspath={{ .Values.args.lnd.tlsPath }}'
            {{- if .Values.args.disableGraph }}- '--disablegraph'{{ end }}
          ports:
            - name: metrics
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
